# Resuscitation {#resuscitation}

## Advanced Life Support

In-hospital resuscitation 
Adult Advanced Life Support 
Tachycardia
Bradycardia 
Paediatric Advanced Life Support
Newborn Life Support

‘Resuscitation‘ can be divided into 2 categories:

Peri-Arrest Patients
Patients in Cardio-Respiratory Arrest
It is very difficult to give one resuscitation plan which can apply to every patient. Each patient will require a tailored treatment plan for their acute insult. Broadly speaking, each critically unwell patient will need basic assessment and investigations to be performed in a bid to gain a diagnosis / differential list while a basic resuscitation is initiated and subsequently tailored as clinical / laboratory information becomes available.

Basic Principles (apply to both categories):

GET HELP IMMEDIATELY – Medical / Nursing / HAN etc
Resuscitation of a patient requires a co-ordinated team response

Follow ABCDE Approach and FREQUENTLY REASSES
A Team Leader should co-ordinate events (usually most senior member of staff)
Gather information – Patient (if able), Notes, Charts, Allergy Bands, Staff on Ward
Communication as a Team is VITAL
During the initial phase of resuscitation, a co-ordinated assessment of ABCDE must occur efficiently with each member of the team appointed to a system(s) or tasks. Often assessments and interventions can be carried synchronously with one person assessing and another attaching monitoring, cannulating and taking bloods etc.

AssessmentInterventions	Interventions
Clinical
Monitoring
Airway	Patent / Talking
Additional Noises (wheeze / stridor)		Airway Positioning (?Link)
Adjuncts
(Nasopharyngeal or Guedel)
Is Definitive Airway Required?
Breathing	Trachea
Inspection
Palpation
Percussion
Auscultation	Saturations Probe
Respiratory Rate	HIGH FLOW OXYGEN
ABG (?Link)
Consider :
Nebulisers
Needle Thoracocentesis
Chest Drain
CPAP / BiPAP
Circulation	Pulse
BP
Skin colour / Temperature
Capillary Refill
Heart Sounds	Cardiac Monitor
BP (NIBP / Arterial)
ECG	2 x LARGE IV ACCESS
Blood samples for Lab
(See Table in Link)
FLUID RESUSCIATION with 500ml boluses of NaCl 0.9%, assessing response each time
Disability	AVPU or GCS
(See Table in Link)
Pupils – Size and Reaction
Posture
Peripheral Neurology		TREATMENT OF ABNORMAL PARAMETERS IN ABC MAY IMPROVE D
Exposure	Temperature
BM
External Signs of Injury
Environmental Clues	Tympanic / Core Temperature
BM Stick +/- Ketone Stick	Antibiotics
Glucose Bolus / Glucagon
REMEMBER TO CONTINUALY REASSES ABCDE AFTER EACH INTERVENTION OR IF ANYTHING CHANGES

Following the basic principles above will allow rapid assessment and stabilisation of the critically ill patient whilst examination and investigations give you an educated differential diagnosis list. There are many acute medical and surgical presentations which shall be covered in the coming chapters.

With all critically unwell patients, consideration of escalation of level of care should be considered. This could be to Coronary Care, High Dependency Unit (Medical or Surgical) or even Intensive Care. The decision to escalate should be made by the most senior members of the team present, bearing in mind that a ceiling of treatment may need to be considered.

The following criteria may guide when it is appropriate to consider referral to the Intensive Care Unit:

Links
SEWS
Shock
Massive Transfusion
Code Red
AVPU or GCS

AVPU
A – Alert and Communicating
V – Responds only to Voice
P – Responds only to Pain
U – Unresponsive

GCS
Score MINIMUM 3 to MAXIMUM 15

E 4           Eyes open spontaneously
E 3           Eyes open to Voice
E 2           Eyes open to Pain
E 1           No opening of the eyes

M 6         Obeys Commands
M 5         Localises to Stimulus
M 4         Flexes to Painful Stimulus
M 3         Abnormal Flexion to Pain
M 2         Extends to Painful Stimulus
M 1         No Motor Response

V 5          Orientated Speech
V 4          Confused content of Speech
V 3          Inappropriate Speech
V 2          Incomprehensible Speech
V 1          No Vocal Response

Even programme where tick boxes and generates number

Blood Samples for Lab
Selected from ICE menu – Think about:

FBC, Co-agulation Screen / INR
U+E’s, Calcium, Magnesium, LFT’s, CRP, Amylase, Troponin
Lactate, Glucose
Group and Save, Cross Match
Blood Cultures – Peripheral and Central

ATOMFC
Acronym for Life-Threatening Airway Insults

A – Airway Loss
T – Tension Pneumothorax
O – Open Pneumothorax
M – Massive Haemothorax
F – Flail Chest
C – Cardiac Tamponade

Advanced Life Support
Code Red
Major Incident / Mass Casualty Incident

## Major Incident
## Haemodynamically Unstable Polytrauma (Code Red)
## Adult Massive Haemorrhage Policy
## Reversing oral anticoagulants in massive haemorrhage