# Pain {#pain}

by Mark Henderson

Pain
Key Contacts
Background Information
Types of pain
How to assess a patient in pain
Management of acute pain
Common analgesics for use in adult patients
Non-opioid analgesics
Common opioid analgesics
Opioid titration and Post-operative nausea guideline
Guidelines for opioid use
Opioid conversion
Approximate opioid equivalence chart
Managing opioid side effects
Opioid toxicity
Excessive sedation and respiratory arrest
Itch
Constipation
Other analgesics and adjuvant therapies
Management of neuropathic pain
Patient Controlled Analgesia
Setting up a PCA
PCA Prescription
PCA Pit-falls
PCA Troubleshooting
PCA Troubleshooting Algorithm
PCA Morphine step down
Epidural analgesia
Background information
Complications
Common problems
Hypotension
Inadequate analgesia
High sensory block
Dense motor block
Leaking epidural
Epidural disconnection
Epidural falling out
Urinary retention
Evolution of other medical problems
How to assess a patient with an epidural
Resources and further reading